// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_PXd7PvjmjigAmy3--m8ErcMMYWIlaQ',
    appId: '1:246865210928:web:4440735f6b50e39d7987f5',
    messagingSenderId: '246865210928',
    projectId: 'musicapp-mytune',
    authDomain: 'musicapp-mytune.firebaseapp.com',
    storageBucket: 'musicapp-mytune.firebasestorage.app',
    measurementId: 'G-FWB0SE8M8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6D7kuHwVXWtc2_1jL4P57DCm8w8r1gVE',
    appId: '1:246865210928:android:fbd71d35ba68fa7e7987f5',
    messagingSenderId: '246865210928',
    projectId: 'musicapp-mytune',
    storageBucket: 'musicapp-mytune.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ED0REKqHDDfw2vSxJiEGH3uAduE0qLE',
    appId: '1:246865210928:ios:9a4f1c3d078243117987f5',
    messagingSenderId: '246865210928',
    projectId: 'musicapp-mytune',
    storageBucket: 'musicapp-mytune.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ED0REKqHDDfw2vSxJiEGH3uAduE0qLE',
    appId: '1:246865210928:ios:9a4f1c3d078243117987f5',
    messagingSenderId: '246865210928',
    projectId: 'musicapp-mytune',
    storageBucket: 'musicapp-mytune.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_PXd7PvjmjigAmy3--m8ErcMMYWIlaQ',
    appId: '1:246865210928:web:c68598fc21eebab57987f5',
    messagingSenderId: '246865210928',
    projectId: 'musicapp-mytune',
    authDomain: 'musicapp-mytune.firebaseapp.com',
    storageBucket: 'musicapp-mytune.firebasestorage.app',
    measurementId: 'G-95RFCJQK9H',
  );
}
